[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_RUNTIME = "nodejs20.x"
  NPM_CONFIG_FETCH_RETRIES = "5"
  NPM_CONFIG_FETCH_RETRY_FACTOR = "2"
  NPM_CONFIG_FETCH_RETRY_MINTIMEOUT = "10000"

# Next.js Image Optimization
[[headers]]
  for = "/_next/image"
  [headers.values]
    Cache-Control = "public, immutable"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes configuration
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Next.js rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Function settings for Next.js API routes
  node_bundler = "esbuild"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

